"""
DataM8
Copyright (C) 2024-2025 ORAYLIS GmbH

This file is part of DataM8.

DataM8 is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

DataM8 is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program. If not, see <https://www.gnu.org/licenses/>.
"""

# generated by datamodel-codegen:
#   filename:  attribute.json

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Annotated, List, Optional

from pydantic import BaseModel, ConfigDict, Field

from . import data_type, property


class HistoryType(Enum):
    """
    Defines how an attribute in a slowly chaning dimension should behave.
    """

    SCD0 = "SCD0"
    SCD1 = "SCD1"
    SCD2 = "SCD2"
    SCD3 = "SCD3"
    SCD4 = "SCD4"


class HasUnit(Enum):
    """
    Defines if an attribute should define a unit, e.g. `Physical` for weight or `Currency` for price.
    """

    NO_UNIT = "NoUnit"
    PHYSICAL = "Physical"
    CURRENCY = "Currency"


class AttributeType(BaseModel):
    """
    Defines abstract business orientated attribute definitions, e.g. an email address
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    name: str
    displayName: Optional[str] = None
    description: Optional[str] = None
    defaultType: str
    defaultLength: Annotated[Optional[int], Field(gt=0)] = None
    defaultPrecision: Annotated[Optional[int], Field(gt=0)] = None
    defaultScale: Annotated[Optional[int], Field(gt=0)] = None
    hasUnit: Annotated[
        Optional[HasUnit],
        Field(
            description="Defines if an attribute should define a unit, e.g. `Physical` for weight or `Currency` for price."
        ),
    ] = HasUnit.NO_UNIT
    canBeInRelation: Optional[bool] = False
    isDefaultProperty: Optional[bool] = False


class Attribute(BaseModel):
    """
    An attribute of a model entity.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    ordinalNumber: Annotated[int, Field(gt=0)]
    name: str
    displayName: Optional[str] = None
    description: Optional[str] = None
    attributeType: str
    dataType: data_type.DataType
    isBusinessKey: Optional[bool] = False
    history: Annotated[
        Optional[HistoryType],
        Field(
            description="Defines how an attribute in a slowly chaning dimension should behave.",
            title="HistoryType",
        ),
    ] = HistoryType.SCD1
    unit: Optional[str] = None
    refactorNames: Optional[List[str]] = None
    dateModified: Optional[datetime] = None
    dateDeleted: Optional[datetime] = None
    dateAdded: datetime
    properties: Optional[List[property.PropertyReference]] = None
