"""
DataM8
Copyright (C) 2024-2025 ORAYLIS GmbH

This file is part of DataM8.

DataM8 is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

DataM8 is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program. If not, see <https://www.gnu.org/licenses/>.
"""

# generated by datamodel-codegen:
#   filename:  base.json

from __future__ import annotations

from enum import Enum
from pathlib import Path
from typing import Annotated, Any, Literal
from collections.abc import Sequence

from pydantic import BaseModel, ConfigDict, Field, RootModel

from . import (
    attribute,
    data_product,
    data_source,
    data_type,
    folder,
    model,
    property,
    zone,
)


class AttributeTypes(BaseModel):
    """
    Defines the layout of entity files within the `Base` folder.
    """

    model_config = ConfigDict(extra="forbid", populate_by_name=True)
    type: Literal["attributeTypes"]
    properties: Any | None = None
    propertyValues: Any | None = None
    zones: Any | None = None
    dataTypes: Any | None = None
    dataSourceTypes: Any | None = None
    dataProducts: Any | None = None
    dataModules: Any | None = None
    attributeTypes: Annotated[Sequence[attribute.AttributeType], Field(min_length=1)]
    dataSources: Any | None = None
    folders: Any | None = None
    modelEntities: Any | None = None

    def to_dict(self) -> dict:
        return self.model_dump(by_alias=True, exclude_unset=True, mode="json")

    @staticmethod
    def from_dict(obj) -> AttributeTypes:
        return AttributeTypes.model_validate(obj, from_attributes=False)

    @staticmethod
    def from_json_file(path: Path) -> AttributeTypes:
        with open(path) as file:
            model = AttributeTypes.model_validate_json(file.read())

        return model


class EntityType(Enum):
    PROPERTIES = "properties"
    PROPERTY_VALUES = "propertyValues"
    ZONES = "zones"
    DATA_TYPES = "dataTypes"
    DATA_SOURCE_TYPES = "dataSourceTypes"
    DATA_PRODUCTS = "dataProducts"
    DATA_MODULES = "dataModules"
    ATTRIBUTE_TYPES = "attributeTypes"
    DATA_SOURCES = "dataSources"
    FOLDERS = "folders"
    MODEL_ENTITIES = "modelEntities"


class PropertyValues(BaseModel):
    """
    Defines the layout of entity files within the `Base` folder.
    """

    model_config = ConfigDict(extra="forbid", populate_by_name=True)
    type: Literal["propertyValues"]
    properties: Any | None = None
    propertyValues: Sequence[property.PropertyValue]
    zones: Any | None = None
    dataTypes: Any | None = None
    dataSourceTypes: Any | None = None
    dataProducts: Any | None = None
    dataModules: Any | None = None
    attributeTypes: Any | None = None
    dataSources: Any | None = None
    folders: Any | None = None
    modelEntities: Any | None = None

    def to_dict(self) -> dict:
        return self.model_dump(by_alias=True, exclude_unset=True, mode="json")

    @staticmethod
    def from_dict(obj) -> PropertyValues:
        return PropertyValues.model_validate(obj, from_attributes=False)

    @staticmethod
    def from_json_file(path: Path) -> PropertyValues:
        with open(path) as file:
            model = PropertyValues.model_validate_json(file.read())

        return model


class Zones(BaseModel):
    """
    Defines the layout of entity files within the `Base` folder.
    """

    model_config = ConfigDict(extra="forbid", populate_by_name=True)
    type: Literal["zones"]
    properties: Any | None = None
    propertyValues: Any | None = None
    zones: Annotated[Sequence[zone.Zone], Field(min_length=1)]
    dataTypes: Any | None = None
    dataSourceTypes: Any | None = None
    dataProducts: Any | None = None
    dataModules: Any | None = None
    attributeTypes: Any | None = None
    dataSources: Any | None = None
    folders: Any | None = None
    modelEntities: Any | None = None

    def to_dict(self) -> dict:
        return self.model_dump(by_alias=True, exclude_unset=True, mode="json")

    @staticmethod
    def from_dict(obj) -> Zones:
        return Zones.model_validate(obj, from_attributes=False)

    @staticmethod
    def from_json_file(path: Path) -> Zones:
        with open(path) as file:
            model = Zones.model_validate_json(file.read())

        return model


class DataTypes(BaseModel):
    """
    Defines the layout of entity files within the `Base` folder.
    """

    model_config = ConfigDict(extra="forbid", populate_by_name=True)
    type: Literal["dataTypes"]
    properties: Any | None = None
    propertyValues: Any | None = None
    zones: Any | None = None
    dataTypes: Annotated[Sequence[data_type.DataTypeDefinition], Field(min_length=1)]
    dataSourceTypes: Any | None = None
    dataProducts: Any | None = None
    dataModules: Any | None = None
    attributeTypes: Any | None = None
    dataSources: Any | None = None
    folders: Any | None = None
    modelEntities: Any | None = None

    def to_dict(self) -> dict:
        return self.model_dump(by_alias=True, exclude_unset=True, mode="json")

    @staticmethod
    def from_dict(obj) -> DataTypes:
        return DataTypes.model_validate(obj, from_attributes=False)

    @staticmethod
    def from_json_file(path: Path) -> DataTypes:
        with open(path) as file:
            model = DataTypes.model_validate_json(file.read())

        return model


class DataSourceTypes(BaseModel):
    """
    Defines the layout of entity files within the `Base` folder.
    """

    model_config = ConfigDict(extra="forbid", populate_by_name=True)
    type: Literal["dataSourceTypes"]
    properties: Any | None = None
    propertyValues: Any | None = None
    zones: Any | None = None
    dataTypes: Any | None = None
    dataSourceTypes: Annotated[
        Sequence[data_source.DataSourceType], Field(min_length=1)
    ]
    dataProducts: Any | None = None
    dataModules: Any | None = None
    attributeTypes: Any | None = None
    dataSources: Any | None = None
    folders: Any | None = None
    modelEntities: Any | None = None

    def to_dict(self) -> dict:
        return self.model_dump(by_alias=True, exclude_unset=True, mode="json")

    @staticmethod
    def from_dict(obj) -> DataSourceTypes:
        return DataSourceTypes.model_validate(obj, from_attributes=False)

    @staticmethod
    def from_json_file(path: Path) -> DataSourceTypes:
        with open(path) as file:
            model = DataSourceTypes.model_validate_json(file.read())

        return model


class Folders(BaseModel):
    """
    Defines the layout of entity files within the `Base` folder.
    """

    model_config = ConfigDict(extra="forbid", populate_by_name=True)
    type: Literal["folders"]
    properties: Any | None = None
    propertyValues: Any | None = None
    zones: Any | None = None
    dataTypes: Any | None = None
    dataSourceTypes: Any | None = None
    dataProducts: Any | None = None
    dataModules: Any | None = None
    attributeTypes: Any | None = None
    dataSources: Any | None = None
    folders: Annotated[Sequence[folder.Folder], Field(min_length=1)]
    modelEntities: Any | None = None

    def to_dict(self) -> dict:
        return self.model_dump(by_alias=True, exclude_unset=True, mode="json")

    @staticmethod
    def from_dict(obj) -> Folders:
        return Folders.model_validate(obj, from_attributes=False)

    @staticmethod
    def from_json_file(path: Path) -> Folders:
        with open(path) as file:
            model = Folders.model_validate_json(file.read())

        return model


class Properties(BaseModel):
    """
    Defines the layout of entity files within the `Base` folder.
    """

    model_config = ConfigDict(extra="forbid", populate_by_name=True)
    type: Literal["properties"]
    properties: Sequence[property.Property]
    propertyValues: Any | None = None
    zones: Any | None = None
    dataTypes: Any | None = None
    dataSourceTypes: Any | None = None
    dataProducts: Any | None = None
    dataModules: Any | None = None
    attributeTypes: Any | None = None
    dataSources: Any | None = None
    folders: Any | None = None
    modelEntities: Any | None = None

    def to_dict(self) -> dict:
        return self.model_dump(by_alias=True, exclude_unset=True, mode="json")

    @staticmethod
    def from_dict(obj) -> Properties:
        return Properties.model_validate(obj, from_attributes=False)

    @staticmethod
    def from_json_file(path: Path) -> Properties:
        with open(path) as file:
            model = Properties.model_validate_json(file.read())

        return model


class DataModules(BaseModel):
    """
    Defines the layout of entity files within the `Base` folder.
    """

    model_config = ConfigDict(extra="forbid", populate_by_name=True)
    type: Literal["dataModules"]
    properties: Any | None = None
    propertyValues: Any | None = None
    zones: Any | None = None
    dataTypes: Any | None = None
    dataSourceTypes: Any | None = None
    dataProducts: Any | None = None
    dataModules: Annotated[Sequence[data_product.DataModule], Field(min_length=1)]
    attributeTypes: Any | None = None
    dataSources: Any | None = None
    folders: Any | None = None
    modelEntities: Any | None = None

    def to_dict(self) -> dict:
        return self.model_dump(by_alias=True, exclude_unset=True, mode="json")

    @staticmethod
    def from_dict(obj) -> DataModules:
        return DataModules.model_validate(obj, from_attributes=False)

    @staticmethod
    def from_json_file(path: Path) -> DataModules:
        with open(path) as file:
            model = DataModules.model_validate_json(file.read())

        return model


class DataSources(BaseModel):
    """
    Defines the layout of entity files within the `Base` folder.
    """

    model_config = ConfigDict(extra="forbid", populate_by_name=True)
    type: Literal["dataSources"]
    properties: Any | None = None
    propertyValues: Any | None = None
    zones: Any | None = None
    dataTypes: Any | None = None
    dataSourceTypes: Any | None = None
    dataProducts: Any | None = None
    dataModules: Any | None = None
    attributeTypes: Any | None = None
    dataSources: Sequence[data_source.DataSource]
    folders: Any | None = None
    modelEntities: Any | None = None

    def to_dict(self) -> dict:
        return self.model_dump(by_alias=True, exclude_unset=True, mode="json")

    @staticmethod
    def from_dict(obj) -> DataSources:
        return DataSources.model_validate(obj, from_attributes=False)

    @staticmethod
    def from_json_file(path: Path) -> DataSources:
        with open(path) as file:
            model = DataSources.model_validate_json(file.read())

        return model


class DataProducts(BaseModel):
    """
    Defines the layout of entity files within the `Base` folder.
    """

    model_config = ConfigDict(extra="forbid", populate_by_name=True)
    type: Literal["dataProducts"]
    properties: Any | None = None
    propertyValues: Any | None = None
    zones: Any | None = None
    dataTypes: Any | None = None
    dataSourceTypes: Any | None = None
    dataProducts: Annotated[Sequence[data_product.DataProduct], Field(min_length=1)]
    dataModules: Any | None = None
    attributeTypes: Any | None = None
    dataSources: Any | None = None
    folders: Any | None = None
    modelEntities: Any | None = None

    def to_dict(self) -> dict:
        return self.model_dump(by_alias=True, exclude_unset=True, mode="json")

    @staticmethod
    def from_dict(obj) -> DataProducts:
        return DataProducts.model_validate(obj, from_attributes=False)

    @staticmethod
    def from_json_file(path: Path) -> DataProducts:
        with open(path) as file:
            model = DataProducts.model_validate_json(file.read())

        return model


class ModelEntities(BaseModel):
    """
    Defines the layout of entity files within the `Base` folder.
    """

    model_config = ConfigDict(extra="forbid", populate_by_name=True)
    type: Literal["modelEntities"]
    properties: Any | None = None
    propertyValues: Any | None = None
    zones: Any | None = None
    dataTypes: Any | None = None
    dataSourceTypes: Any | None = None
    dataProducts: Any | None = None
    dataModules: Any | None = None
    attributeTypes: Any | None = None
    dataSources: Any | None = None
    folders: Any | None = None
    modelEntities: Sequence[model.ModelEntity]

    def to_dict(self) -> dict:
        return self.model_dump(by_alias=True, exclude_unset=True, mode="json")

    @staticmethod
    def from_dict(obj) -> ModelEntities:
        return ModelEntities.model_validate(obj, from_attributes=False)

    @staticmethod
    def from_json_file(path: Path) -> ModelEntities:
        with open(path) as file:
            model = ModelEntities.model_validate_json(file.read())

        return model


type BaseEntitiesType = ModelEntities | Folders | Properties | PropertyValues | Zones | DataTypes | DataSourceTypes | DataProducts | DataModules | AttributeTypes | DataSources
"""
Defines the layout of entity files within the `Base` folder.
"""


class BaseEntities(
    RootModel[
        ModelEntities
        | Folders
        | Properties
        | PropertyValues
        | Zones
        | DataTypes
        | DataSourceTypes
        | DataProducts
        | DataModules
        | AttributeTypes
        | DataSources
    ]
):
    root: Annotated[
        ModelEntities
        | Folders
        | Properties
        | PropertyValues
        | Zones
        | DataTypes
        | DataSourceTypes
        | DataProducts
        | DataModules
        | AttributeTypes
        | DataSources,
        Field(title="BaseEntities"),
    ]
    """
    Defines the layout of entity files within the `Base` folder.
    """

    @staticmethod
    def from_json_file(path: Path) -> BaseEntities:
        with open(path) as file:
            model = BaseEntities.model_validate_json(file.read())

        return model


type BaseEntityType = property.Property | property.PropertyValue | zone.Zone | data_type.DataType | data_type.DataTypeDefinition | data_source.DataSourceType | data_product.DataProduct | data_product.DataModule | attribute.AttributeType | data_source.DataSource | folder.Folder | model.ModelEntity
"""
A union type for all internal objects.
"""


class BaseEntity(
    RootModel[
        property.Property
        | property.PropertyValue
        | zone.Zone
        | data_type.DataType
        | data_type.DataTypeDefinition
        | data_source.DataSourceType
        | data_product.DataProduct
        | data_product.DataModule
        | attribute.AttributeType
        | data_source.DataSource
        | folder.Folder
        | model.ModelEntity
    ]
):
    root: (
        property.Property
        | property.PropertyValue
        | zone.Zone
        | data_type.DataType
        | data_type.DataTypeDefinition
        | data_source.DataSourceType
        | data_product.DataProduct
        | data_product.DataModule
        | attribute.AttributeType
        | data_source.DataSource
        | folder.Folder
        | model.ModelEntity
    )
    """
    A union type for all internal objects.
    """

    @staticmethod
    def from_json_file(path: Path) -> BaseEntity:
        with open(path) as file:
            model = BaseEntity.model_validate_json(file.read())

        return model
