"""
DataM8
Copyright (C) 2024-2025 ORAYLIS GmbH

This file is part of DataM8.

DataM8 is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

DataM8 is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program. If not, see <https://www.gnu.org/licenses/>.
"""

# generated by datamodel-codegen:
#   filename:  base.json

from __future__ import annotations

from enum import Enum
from typing import Annotated, Any, List, Literal, Optional, Union

from pydantic import BaseModel, ConfigDict, Field, RootModel

from . import (
    attribute,
    data_product,
    data_source,
    data_type,
    folder,
    model,
    property,
    zone,
)


class AttributeTypes(BaseModel):
    """
    Defines the layout of entity files within the `Base` folder.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    type: Literal["attributeTypes"]
    properties: Optional[Any] = None
    propertyTypes: Optional[Any] = None
    zones: Optional[Any] = None
    dataTypes: Optional[Any] = None
    dataSourceTypes: Optional[Any] = None
    dataProducts: Optional[Any] = None
    dataModules: Optional[Any] = None
    attributeTypes: List[attribute.AttributeType]
    dataSources: Optional[Any] = None
    folders: Optional[Any] = None
    modelEntities: Optional[Any] = None


class EntityType(Enum):
    PROPERTIES = "properties"
    PROPERTY_TYPES = "propertyTypes"
    ZONES = "zones"
    DATA_TYPES = "dataTypes"
    DATA_SOURCE_TYPES = "dataSourceTypes"
    DATA_PRODUCTS = "dataProducts"
    DATA_MODULES = "dataModules"
    ATTRIBUTE_TYPES = "attributeTypes"
    DATA_SOURCES = "dataSources"
    FOLDERS = "folders"
    MODEL_ENTITIES = "modelEntities"


class PropertyType(BaseModel):
    """
    Defines the layout of entity files within the `Base` folder.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    type: Literal["propertyTypes"]
    properties: Optional[Any] = None
    propertyTypes: List[property.PropertyType]
    zones: Optional[Any] = None
    dataTypes: Optional[Any] = None
    dataSourceTypes: Optional[Any] = None
    dataProducts: Optional[Any] = None
    dataModules: Optional[Any] = None
    attributeTypes: Optional[Any] = None
    dataSources: Optional[Any] = None
    folders: Optional[Any] = None
    modelEntities: Optional[Any] = None


class Zones(BaseModel):
    """
    Defines the layout of entity files within the `Base` folder.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    type: Literal["zones"]
    properties: Optional[Any] = None
    propertyTypes: Optional[Any] = None
    zones: List[zone.Zone]
    dataTypes: Optional[Any] = None
    dataSourceTypes: Optional[Any] = None
    dataProducts: Optional[Any] = None
    dataModules: Optional[Any] = None
    attributeTypes: Optional[Any] = None
    dataSources: Optional[Any] = None
    folders: Optional[Any] = None
    modelEntities: Optional[Any] = None


class DataTypes(BaseModel):
    """
    Defines the layout of entity files within the `Base` folder.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    type: Literal["dataTypes"]
    properties: Optional[Any] = None
    propertyTypes: Optional[Any] = None
    zones: Optional[Any] = None
    dataTypes: List[data_type.DataTypeDefinition]
    dataSourceTypes: Optional[Any] = None
    dataProducts: Optional[Any] = None
    dataModules: Optional[Any] = None
    attributeTypes: Optional[Any] = None
    dataSources: Optional[Any] = None
    folders: Optional[Any] = None
    modelEntities: Optional[Any] = None


class DataSourceTypes(BaseModel):
    """
    Defines the layout of entity files within the `Base` folder.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    type: Literal["dataSourceTypes"]
    properties: Optional[Any] = None
    propertyTypes: Optional[Any] = None
    zones: Optional[Any] = None
    dataTypes: Optional[Any] = None
    dataSourceTypes: List[data_source.DataSourceType]
    dataProducts: Optional[Any] = None
    dataModules: Optional[Any] = None
    attributeTypes: Optional[Any] = None
    dataSources: Optional[Any] = None
    folders: Optional[Any] = None
    modelEntities: Optional[Any] = None


class Folders(BaseModel):
    """
    Defines the layout of entity files within the `Base` folder.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    type: Literal["folders"]
    properties: Optional[Any] = None
    propertyTypes: Optional[Any] = None
    zones: Optional[Any] = None
    dataTypes: Optional[Any] = None
    dataSourceTypes: Optional[Any] = None
    dataProducts: Optional[Any] = None
    dataModules: Optional[Any] = None
    attributeTypes: Optional[Any] = None
    dataSources: Optional[Any] = None
    folders: List[folder.Folder]
    modelEntities: Optional[Any] = None


class Properties(BaseModel):
    """
    Defines the layout of entity files within the `Base` folder.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    type: Literal["properties"]
    properties: List[property.Property]
    propertyTypes: Optional[Any] = None
    zones: Optional[Any] = None
    dataTypes: Optional[Any] = None
    dataSourceTypes: Optional[Any] = None
    dataProducts: Optional[Any] = None
    dataModules: Optional[Any] = None
    attributeTypes: Optional[Any] = None
    dataSources: Optional[Any] = None
    folders: Optional[Any] = None
    modelEntities: Optional[Any] = None


class DataModules(BaseModel):
    """
    Defines the layout of entity files within the `Base` folder.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    type: Literal["dataModules"]
    properties: Optional[Any] = None
    propertyTypes: Optional[Any] = None
    zones: Optional[Any] = None
    dataTypes: Optional[Any] = None
    dataSourceTypes: Optional[Any] = None
    dataProducts: Optional[Any] = None
    dataModules: List[data_product.DataModule]
    attributeTypes: Optional[Any] = None
    dataSources: Optional[Any] = None
    folders: Optional[Any] = None
    modelEntities: Optional[Any] = None


class DataSources(BaseModel):
    """
    Defines the layout of entity files within the `Base` folder.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    type: Literal["dataSources"]
    properties: Optional[Any] = None
    propertyTypes: Optional[Any] = None
    zones: Optional[Any] = None
    dataTypes: Optional[Any] = None
    dataSourceTypes: Optional[Any] = None
    dataProducts: Optional[Any] = None
    dataModules: Optional[Any] = None
    attributeTypes: Optional[Any] = None
    dataSources: List[data_source.DataSource]
    folders: Optional[Any] = None
    modelEntities: Optional[Any] = None


class DataProducts(BaseModel):
    """
    Defines the layout of entity files within the `Base` folder.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    type: Literal["dataProducts"]
    properties: Optional[Any] = None
    propertyTypes: Optional[Any] = None
    zones: Optional[Any] = None
    dataTypes: Optional[Any] = None
    dataSourceTypes: Optional[Any] = None
    dataProducts: List[data_product.DataProduct]
    dataModules: Optional[Any] = None
    attributeTypes: Optional[Any] = None
    dataSources: Optional[Any] = None
    folders: Optional[Any] = None
    modelEntities: Optional[Any] = None


class ModelEntities(BaseModel):
    """
    Defines the layout of entity files within the `Base` folder.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    type: Literal["modelEntities"]
    properties: Optional[Any] = None
    propertyTypes: Optional[Any] = None
    zones: Optional[Any] = None
    dataTypes: Optional[Any] = None
    dataSourceTypes: Optional[Any] = None
    dataProducts: Optional[Any] = None
    dataModules: Optional[Any] = None
    attributeTypes: Optional[Any] = None
    dataSources: Optional[Any] = None
    folders: Optional[Any] = None
    modelEntities: List[model.ModelEntity]


class BaseEntity(
    RootModel[
        Union[
            ModelEntities,
            Folders,
            Properties,
            PropertyType,
            Zones,
            DataTypes,
            DataSourceTypes,
            DataProducts,
            DataModules,
            AttributeTypes,
            DataSources,
        ]
    ]
):
    root: Annotated[
        Union[
            ModelEntities,
            Folders,
            Properties,
            PropertyType,
            Zones,
            DataTypes,
            DataSourceTypes,
            DataProducts,
            DataModules,
            AttributeTypes,
            DataSources,
        ],
        Field(
            description="Defines the layout of entity files within the `Base` folder.",
            title="BaseEntity",
        ),
    ]
