"""
DataM8
Copyright (C) 2024-2025 ORAYLIS GmbH

This file is part of DataM8.

DataM8 is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

DataM8 is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program. If not, see <https://www.gnu.org/licenses/>.
"""

# generated by datamodel-codegen:
#   filename:  data-type.json

from __future__ import annotations

from typing import Annotated, Optional

from pydantic import BaseModel, ConfigDict, Field


class DataType(BaseModel):
    """
    An datam8 abstract internal data type.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    type: str
    nullable: bool
    charLen: Annotated[Optional[int], Field(gt=0)] = None
    precision: Annotated[Optional[int], Field(gt=0)] = None
    scale: Annotated[Optional[int], Field(gt=0)] = None


class DataTypeDefinition(BaseModel):
    """
    Defines a class of data type to configure which `DataType` properties are relevant for a specific type.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    name: str
    displayName: Optional[str] = None
    description: Optional[str] = None
    hasCharLen: Optional[bool] = False
    hasPrecision: Optional[bool] = False
    hasScale: Optional[bool] = False
    parquetType: Annotated[
        str,
        Field(
            description="The actual parquet data type that this datam8 internal type will map to."
        ),
    ]
    sqlType: Annotated[
        str,
        Field(
            description="The atual sql data type that this datam8 internal type will map to."
        ),
    ]
