"""
DataM8
Copyright (C) 2024-2025 ORAYLIS GmbH

This file is part of DataM8.

DataM8 is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

DataM8 is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program. If not, see <https://www.gnu.org/licenses/>.
"""

# generated by datamodel-codegen:
#   filename:  data-type.json

from __future__ import annotations

from pathlib import Path
from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field


class DataType(BaseModel):
    """
    An datam8 abstract internal data type.
    """

    model_config = ConfigDict(extra="forbid", populate_by_name=True)
    type: str
    nullable: bool
    charLen: Annotated[int | None, Field(gt=0)] = None
    precision: Annotated[int | None, Field(gt=0)] = None
    scale: Annotated[int | None, Field(gt=0)] = None

    def to_dict(self) -> dict:
        return self.model_dump(by_alias=True, exclude_unset=True, mode="json")

    @staticmethod
    def from_dict(obj) -> DataType:
        return DataType.model_validate(obj, from_attributes=False)

    @staticmethod
    def from_json_file(path: Path) -> DataType:
        with open(path) as file:
            model = DataType.model_validate_json(file.read())

        return model


class DataTypeDefinition(BaseModel):
    """
    Defines a class of data type to configure which `DataType` properties are relevant for a specific type.
    """

    model_config = ConfigDict(extra="forbid", populate_by_name=True)
    name: str
    displayName: str | None = None
    description: str | None = None
    hasCharLen: bool | None = False
    hasPrecision: bool | None = False
    hasScale: bool | None = False
    parquetType: str
    """
    The actual parquet data type that this datam8 internal type will map to.
    """
    sqlType: str
    """
    The atual sql data type that this datam8 internal type will map to.
    """

    def to_dict(self) -> dict:
        return self.model_dump(by_alias=True, exclude_unset=True, mode="json")

    @staticmethod
    def from_dict(obj) -> DataTypeDefinition:
        return DataTypeDefinition.model_validate(obj, from_attributes=False)

    @staticmethod
    def from_json_file(path: Path) -> DataTypeDefinition:
        with open(path) as file:
            model = DataTypeDefinition.model_validate_json(file.read())

        return model
