"""
DataM8
Copyright (C) 2024-2025 ORAYLIS GmbH

This file is part of DataM8.

DataM8 is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

DataM8 is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program. If not, see <https://www.gnu.org/licenses/>.
"""

# generated by datamodel-codegen:
#   filename:  data-source.json

from __future__ import annotations

from typing import Annotated, Dict, List, Optional

from pydantic import BaseModel, ConfigDict, Field

from . import property


class SourceDataTypeMapping(BaseModel):
    """
    A mapping of datatypes name in the source to datam8 internal datatype names.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    sourceType: Annotated[str, Field(description="Source system data type")]
    targetType: Annotated[str, Field(description="Target system data type")]


class ConnectionProperty(BaseModel):
    """
    A property or setting defined by a data source type, which is then available when defining concret data sources.
    """

    name: str
    required: bool
    description: Optional[str] = None


class DataSourceType(BaseModel):
    """
    Defines groups of data sources that base on their technology, e.g. `SqlServer` or `Oracle`
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    name: Annotated[
        str,
        Field(
            description="Name of the data source type (e.g., SqlDataSource, LakeSource)"
        ),
    ]
    displayName: Annotated[
        Optional[str], Field(description="Human-readable display name")
    ] = None
    description: Annotated[
        Optional[str], Field(description="Description of the data source type")
    ] = None
    dataTypeMapping: Annotated[
        List[SourceDataTypeMapping],
        Field(
            description="Default data type mappings for this source type", min_length=1
        ),
    ]
    connectionProperties: Annotated[
        Optional[List[ConnectionProperty]],
        Field(description="Required connection properties for this source type"),
    ] = None


class DataSource(BaseModel):
    """
    Defines an external source of data to be loaded with datam8.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    name: str
    displayName: Optional[str] = None
    description: Optional[str] = None
    properties: Optional[List[property.PropertyReference]] = None
    type: str
    connectionString: Optional[str] = None
    dataTypeMapping: Annotated[
        Optional[List[SourceDataTypeMapping]],
        Field(
            description="Optional data type mappings. If not specified, uses defaults from DataSourceTypes. Individual mappings override defaults."
        ),
    ] = None
    extendedProperties: Annotated[
        Optional[Dict[str, str]],
        Field(description="Additional properties specific to the data source"),
    ] = None
