"""
DataM8
Copyright (C) 2024-2025 ORAYLIS GmbH

This file is part of DataM8.

DataM8 is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

DataM8 is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program. If not, see <https://www.gnu.org/licenses/>.
"""

# generated by datamodel-codegen:
#   filename:  data-source.json

from __future__ import annotations

from pathlib import Path
from typing import Annotated
from collections.abc import Mapping, Sequence

from pydantic import BaseModel, ConfigDict, Field

from . import property


class SourceDataTypeMapping(BaseModel):
    """
    A mapping of datatypes name in the source to datam8 internal datatype names.
    """

    model_config = ConfigDict(extra="forbid", populate_by_name=True)
    sourceType: str
    """
    Source system data type
    """
    targetType: str
    """
    Target system data type
    """

    def to_dict(self) -> dict:
        return self.model_dump(by_alias=True, exclude_unset=True, mode="json")

    @staticmethod
    def from_dict(obj) -> SourceDataTypeMapping:
        return SourceDataTypeMapping.model_validate(obj, from_attributes=False)

    @staticmethod
    def from_json_file(path: Path) -> SourceDataTypeMapping:
        """Loads ands validates a json file from the given path.

        Parameters
        ----------
        path : Path
          The path to the json to be loaded into the model.

        Returns
        -------
        SourceDataTypeMapping
            Instantiated and validated pydantic model

        Raises
        ------
        ValidationError
            If the data in the json file does not much the model constraints.
        """
        with open(path) as file:
            model = SourceDataTypeMapping.model_validate_json(file.read())

        return model


class ConnectionProperty(BaseModel):
    """
    A property or setting defined by a data source type, which is then available when defining concret data sources.
    """

    name: str
    required: bool
    description: str | None = None

    def to_dict(self) -> dict:
        return self.model_dump(by_alias=True, exclude_unset=True, mode="json")

    @staticmethod
    def from_dict(obj) -> ConnectionProperty:
        return ConnectionProperty.model_validate(obj, from_attributes=False)

    @staticmethod
    def from_json_file(path: Path) -> ConnectionProperty:
        """Loads ands validates a json file from the given path.

        Parameters
        ----------
        path : Path
          The path to the json to be loaded into the model.

        Returns
        -------
        ConnectionProperty
            Instantiated and validated pydantic model

        Raises
        ------
        ValidationError
            If the data in the json file does not much the model constraints.
        """
        with open(path) as file:
            model = ConnectionProperty.model_validate_json(file.read())

        return model


class DataSourceType(BaseModel):
    """
    Defines groups of data sources that base on their technology, e.g. `SqlServer` or `Oracle`
    """

    model_config = ConfigDict(extra="forbid", populate_by_name=True)
    name: str
    """
    Name of the data source type (e.g., SqlDataSource, LakeSource)
    """
    displayName: str | None = None
    """
    Human-readable display name
    """
    description: str | None = None
    """
    Description of the data source type
    """
    dataTypeMapping: Annotated[Sequence[SourceDataTypeMapping], Field(min_length=1)]
    """
    Default data type mappings for this source type
    """
    connectionProperties: Sequence[ConnectionProperty] | None = None
    """
    Required connection properties for this source type
    """

    def to_dict(self) -> dict:
        return self.model_dump(by_alias=True, exclude_unset=True, mode="json")

    @staticmethod
    def from_dict(obj) -> DataSourceType:
        return DataSourceType.model_validate(obj, from_attributes=False)

    @staticmethod
    def from_json_file(path: Path) -> DataSourceType:
        """Loads ands validates a json file from the given path.

        Parameters
        ----------
        path : Path
          The path to the json to be loaded into the model.

        Returns
        -------
        DataSourceType
            Instantiated and validated pydantic model

        Raises
        ------
        ValidationError
            If the data in the json file does not much the model constraints.
        """
        with open(path) as file:
            model = DataSourceType.model_validate_json(file.read())

        return model


class DataSource(BaseModel):
    """
    Defines an external source of data to be loaded with datam8.
    """

    model_config = ConfigDict(extra="forbid", populate_by_name=True)
    name: str
    displayName: str | None = None
    description: str | None = None
    properties: Sequence[property.PropertyReference] | None = None
    type: str
    connectionString: str | None = None
    dataTypeMapping: Sequence[SourceDataTypeMapping] | None = None
    """
    Optional data type mappings. If not specified, uses defaults from DataSourceTypes. Individual mappings override defaults.
    """
    extendedProperties: Mapping[str, str] | None = None
    """
    Additional properties specific to the data source
    """

    def to_dict(self) -> dict:
        return self.model_dump(by_alias=True, exclude_unset=True, mode="json")

    @staticmethod
    def from_dict(obj) -> DataSource:
        return DataSource.model_validate(obj, from_attributes=False)

    @staticmethod
    def from_json_file(path: Path) -> DataSource:
        """Loads ands validates a json file from the given path.

        Parameters
        ----------
        path : Path
          The path to the json to be loaded into the model.

        Returns
        -------
        DataSource
            Instantiated and validated pydantic model

        Raises
        ------
        ValidationError
            If the data in the json file does not much the model constraints.
        """
        with open(path) as file:
            model = DataSource.model_validate_json(file.read())

        return model
