"""
DataM8
Copyright (C) 2024-2025 ORAYLIS GmbH

This file is part of DataM8.

DataM8 is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

DataM8 is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program. If not, see <https://www.gnu.org/licenses/>.
"""

# generated by datamodel-codegen:
#   filename:  model.json

from __future__ import annotations

from enum import Enum
from pathlib import Path
from typing import Annotated, Any, Dict, List, TypeAlias

from pydantic import BaseModel, ConfigDict, Field

from . import attribute, data_type, property


class Locator(BaseModel):
    """
    Describes an abstract way to point to and find entities with datam8.
    """

    model_config = ConfigDict(extra="forbid", populate_by_name=True)
    zone: str
    """
    Reference to the top-level folder within the model folder.
    """
    folders: List[str]
    """
    Hierarchical list of olders under the zone. Order is relevant.
    """
    modelEntity: str
    """
    Name property of the modelEntity object.
    """

    def to_dict(self) -> dict:
        return self.model_dump(by_alias=True, exclude_unset=True, mode="json")

    @staticmethod
    def from_dict(obj) -> "Locator":
        return Locator.model_validate(obj, from_attributes=False)

    @staticmethod
    def from_json_file(path: Path) -> "Locator":
        with open(path, "r") as file:
            model = Locator.model_validate_json(file.read())

        return model


class ModelParameter(BaseModel):
    """
    Key-Value pair parameters for customization of and entity-level attributes.
    """

    model_config = ConfigDict(extra="forbid", populate_by_name=True)
    name: str
    value: str | Dict[str, Any] | float | bool

    def to_dict(self) -> dict:
        return self.model_dump(by_alias=True, exclude_unset=True, mode="json")

    @staticmethod
    def from_dict(obj) -> "ModelParameter":
        return ModelParameter.model_validate(obj, from_attributes=False)

    @staticmethod
    def from_json_file(path: Path) -> "ModelParameter":
        with open(path, "r") as file:
            model = ModelParameter.model_validate_json(file.read())

        return model


class TransformationKind(Enum):
    """
    Type of transformation, either `builtin` or `function`.
    """

    BUILTIN = "builtin"
    FUNCTION = "function"


class TransformationFunction(BaseModel):
    """
    A transformation function defined in the scope of the current solution.
    """

    model_config = ConfigDict(extra="forbid", populate_by_name=True)
    source: str

    def to_dict(self) -> dict:
        return self.model_dump(by_alias=True, exclude_unset=True, mode="json")

    @staticmethod
    def from_dict(obj) -> "TransformationFunction":
        return TransformationFunction.model_validate(obj, from_attributes=False)

    @staticmethod
    def from_json_file(path: Path) -> "TransformationFunction":
        with open(path, "r") as file:
            model = TransformationFunction.model_validate_json(file.read())

        return model


class SourceAttributeMapping(BaseModel):
    """
    Map an attribute in the source to one in the current entity. May optionally contain an explicit source data type.
    """

    model_config = ConfigDict(extra="forbid", populate_by_name=True)
    targetName: str
    sourceName: str
    sourceDataType: data_type.DataType | None = None
    properties: List[property.PropertyReference] | None = None

    def to_dict(self) -> dict:
        return self.model_dump(by_alias=True, exclude_unset=True, mode="json")

    @staticmethod
    def from_dict(obj) -> "SourceAttributeMapping":
        return SourceAttributeMapping.model_validate(obj, from_attributes=False)

    @staticmethod
    def from_json_file(path: Path) -> "SourceAttributeMapping":
        with open(path, "r") as file:
            model = SourceAttributeMapping.model_validate_json(file.read())

        return model


class ModelTransformation(BaseModel):
    """
    Describes a single transformation, either builtin or defined within the solution.
    """

    model_config = ConfigDict(extra="forbid", populate_by_name=True)
    stepNo: Annotated[int, Field(ge=1)]
    kind: Annotated[TransformationKind, Field(title="TransformationKind")]
    """
    Type of transformation, either `builtin` or `function`.
    """
    name: str
    properties: List[property.PropertyReference] | None = None
    function: Annotated[
        TransformationFunction | None, Field(title="TransformationFunction")
    ] = None
    """
    A transformation function defined in the scope of the current solution.
    """

    def to_dict(self) -> dict:
        return self.model_dump(by_alias=True, exclude_unset=True, mode="json")

    @staticmethod
    def from_dict(obj) -> "ModelTransformation":
        return ModelTransformation.model_validate(obj, from_attributes=False)

    @staticmethod
    def from_json_file(path: Path) -> "ModelTransformation":
        with open(path, "r") as file:
            model = ModelTransformation.model_validate_json(file.read())

        return model


class InternalModelSource(BaseModel):
    """
    Internal source definition to reference other entities within datam8.
    """

    model_config = ConfigDict(extra="forbid", populate_by_name=True)
    sourceLocation: str | int
    properties: List[property.PropertyReference] | None = None
    mapping: List[SourceAttributeMapping] | None = None

    def to_dict(self) -> dict:
        return self.model_dump(by_alias=True, exclude_unset=True, mode="json")

    @staticmethod
    def from_dict(obj) -> "InternalModelSource":
        return InternalModelSource.model_validate(obj, from_attributes=False)

    @staticmethod
    def from_json_file(path: Path) -> "InternalModelSource":
        with open(path, "r") as file:
            model = InternalModelSource.model_validate_json(file.read())

        return model


class ExternalModelSource(BaseModel):
    """
    Sources that point to external systems outside of datam8.
    """

    model_config = ConfigDict(extra="forbid", populate_by_name=True)
    dataSource: str
    sourceLocation: str
    properties: List[property.PropertyReference] | None = None
    mapping: List[SourceAttributeMapping] | None = None

    def to_dict(self) -> dict:
        return self.model_dump(by_alias=True, exclude_unset=True, mode="json")

    @staticmethod
    def from_dict(obj) -> "ExternalModelSource":
        return ExternalModelSource.model_validate(obj, from_attributes=False)

    @staticmethod
    def from_json_file(path: Path) -> "ExternalModelSource":
        with open(path, "r") as file:
            model = ExternalModelSource.model_validate_json(file.read())

        return model


class ModelEntity(BaseModel):
    """
    Describes a single entity within datam8. Most commonly a database table.
    """

    model_config = ConfigDict(extra="forbid", populate_by_name=True)
    id: Annotated[int, Field(gt=0)]
    """
    Internal id of an entity.
    """
    name: str
    displayName: str | None = None
    description: str | None = None
    parameters: List[ModelParameter] | None = None
    attributes: Annotated[List[attribute.Attribute], Field(min_length=1)]
    properties: List[property.PropertyReference] | None = None
    sources: Annotated[
        List[InternalModelSource | ExternalModelSource], Field(min_length=1)
    ]
    transformations: Annotated[List[ModelTransformation], Field(min_length=1)]
    """
    List of transformations that will be executed in order of stepNo.
    """

    def to_dict(self) -> dict:
        return self.model_dump(by_alias=True, exclude_unset=True, mode="json")

    @staticmethod
    def from_dict(obj) -> "ModelEntity":
        return ModelEntity.model_validate(obj, from_attributes=False)

    @staticmethod
    def from_json_file(path: Path) -> "ModelEntity":
        with open(path, "r") as file:
            model = ModelEntity.model_validate_json(file.read())

        return model
