"""
DataM8
Copyright (C) 2024-2025 ORAYLIS GmbH

This file is part of DataM8.

DataM8 is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

DataM8 is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program. If not, see <https://www.gnu.org/licenses/>.
"""

# generated by datamodel-codegen:
#   filename:  model.json

from __future__ import annotations

from enum import Enum
from typing import Annotated, Any, Dict, List, Optional, Union

from pydantic import BaseModel, ConfigDict, Field

from . import attribute, data_type, property


class Locator(BaseModel):
    """
    Describes an abstract way to point to and find entities with datam8.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    id: Annotated[int, Field(description="Internal id of an entity.", gt=0)]
    zone: Annotated[
        str,
        Field(description="Reference to the top-level folder within the model folder."),
    ]
    folders: Annotated[
        List[str],
        Field(
            description="Hierarchical list of olders under the zone. Order is relevant."
        ),
    ]
    modelEntity: Annotated[
        str, Field(description="Name property of the modelEntity object.")
    ]


class ModelParameter(BaseModel):
    """
    Key-Value pair parameters for customization of and entity-level attributes.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    name: str
    value: Union[str, Dict[str, Any], float, bool]


class TransformationKind(Enum):
    """
    Type of transformation, either `builtin` or `function`.
    """

    BUILTIN = "builtin"
    FUNCTION = "function"


class TransformationFunction(BaseModel):
    """
    A transformation function defined in the scope of the current solution.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    source: str


class SourceAttributeMapping(BaseModel):
    """
    Map an attribute in the source to one in the current entity. May optionally contain an explicit source data type.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    targetName: str
    sourceName: str
    sourceDataType: Optional[data_type.DataType] = None
    properties: Optional[List[property.PropertyReference]] = None


class ModelTransformation(BaseModel):
    """
    Describes a single transformation, either builtin or defined within the solution.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    stepNo: Annotated[int, Field(ge=1)]
    kind: Annotated[
        TransformationKind,
        Field(
            description="Type of transformation, either `builtin` or `function`.",
            title="TransformationKind",
        ),
    ]
    name: str
    properties: Optional[List[property.PropertyReference]] = None
    function: Annotated[
        Optional[TransformationFunction],
        Field(
            description="A transformation function defined in the scope of the current solution.",
            title="TransformationFunction",
        ),
    ] = None


class InternalModelSource(BaseModel):
    """
    Internal source definition to reference other entities within datam8.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    sourceLocation: Union[str, int]
    properties: Optional[List[property.PropertyReference]] = None
    mapping: Optional[List[SourceAttributeMapping]] = None


class ExternalModelSource(BaseModel):
    """
    Sources that point to external systems outside of datam8.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    dataSource: str
    sourceLocation: str
    properties: Optional[List[property.PropertyReference]] = None
    mapping: Optional[List[SourceAttributeMapping]] = None


class ModelEntity(BaseModel):
    """
    Describes a single entity within datam8. Most commonly a database table.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    id: Annotated[int, Field(description="Internal id of an entity.", gt=0)]
    name: str
    displayName: Optional[str] = None
    description: Optional[str] = None
    parameters: Optional[List[ModelParameter]] = None
    attributes: Annotated[List[attribute.Attribute], Field(min_length=1)]
    properties: Optional[List[property.PropertyReference]] = None
    sources: Annotated[
        List[Union[InternalModelSource, ExternalModelSource]], Field(min_length=1)
    ]
    transformations: Annotated[
        List[ModelTransformation],
        Field(
            description="List of transformations that will be executed in order of stepNo.",
            min_length=1,
        ),
    ]
