"""
DataM8
Copyright (C) 2024-2025 ORAYLIS GmbH

This file is part of DataM8.

DataM8 is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

DataM8 is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program. If not, see <https://www.gnu.org/licenses/>.
"""

# generated by datamodel-codegen:
#   filename:  property.json

from __future__ import annotations

from typing import Annotated, List, Optional

from pydantic import BaseModel, ConfigDict, Field


class PropertyReference(BaseModel):
    """
    Used to reference from any entity to a `Property`.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    type: str
    value: str


class PropertyScope(BaseModel):
    """
    Defines for which type of entities a `PropertyType` is available for assignment.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    type: str
    singleUsage: Annotated[
        Optional[bool],
        Field(
            description="Defines if the `PropertyType` can only be assigned once to entities in this scope."
        ),
    ] = True
    mandatory: Optional[bool] = False


class PropertyType(BaseModel):
    """
    Defines a group of Properties that are grouped together for selection purposes.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    name: str
    displayName: Optional[str] = None
    schema_: Annotated[Optional[str], Field(alias="schema")] = None
    scopes: Optional[List[PropertyScope]] = []


class Property(BaseModel):
    """
    A single globally available static attribute that can be referenced from other entities.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    name: str
    displayName: Optional[str] = None
    default: Optional[bool] = False
    type: str
    properties: Optional[List[PropertyReference]] = None
