"""
DataM8
Copyright (C) 2024-2025 ORAYLIS GmbH

This file is part of DataM8.

DataM8 is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

DataM8 is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program. If not, see <https://www.gnu.org/licenses/>.
"""

# generated by datamodel-codegen:
#   filename:  solution.json

from __future__ import annotations

from typing import Annotated, Optional

from pydantic import BaseModel, ConfigDict, Field


class Solution(BaseModel):
    """
    A definition to hold various settings for use in the frontend or the generator.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    schemaVersion: Annotated[
        str,
        Field(
            description="Version of the schema for validation and migration support."
        ),
    ]
    modelPath: Annotated[
        Optional[str],
        Field(
            description="Root path for model entities, replacing zone-specific paths."
        ),
    ] = "Model"
    basePath: Annotated[
        Optional[str],
        Field(description="Path where base entity files like DataSources are stored."),
    ] = "Base"
    generatePath: Annotated[
        Optional[str],
        Field(
            description="Path containing templates and additional code for their rendering."
        ),
    ] = "Generate"
    diagramPath: Annotated[Optional[str], Field(description="tbd")] = "Diagram"
    outputPath: Annotated[
        Optional[str], Field(description="Path for storing generated output.")
    ] = "Output"
