"""
DataM8
Copyright (C) 2024-2025 ORAYLIS GmbH

This file is part of DataM8.

DataM8 is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

DataM8 is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program. If not, see <https://www.gnu.org/licenses/>.
"""

# generated by datamodel-codegen:
#   filename:  zone.json

from __future__ import annotations

from pathlib import Path

from pydantic import BaseModel, ConfigDict


class Zone(BaseModel):
    """
    Defines a high-level layer or zone, typically used to clearly seperate different states of data processing, e.g. bronze, silver, gold, semantic.
    """

    model_config = ConfigDict(extra="forbid", populate_by_name=True)
    name: str
    """
    Logical name of the zone (e.g., Raw, Core, Curated)
    """
    targetName: str
    """
    Target system name for the zone (e.g., Bronze, Silver, Gold)
    """
    displayName: str
    """
    Human-readable display name
    """
    localFolderName: str | None = None
    """
    Local folder name used in file system structure
    """

    def to_dict(self) -> dict:
        return self.model_dump(by_alias=True, exclude_unset=True, mode="json")

    @staticmethod
    def from_dict(obj) -> Zone:
        return Zone.model_validate(obj, from_attributes=False)

    @staticmethod
    def from_json_file(path: Path) -> Zone:
        with open(path) as file:
            model = Zone.model_validate_json(file.read())

        return model
