"""
DataM8
Copyright (C) 2024-2025 ORAYLIS GmbH

This file is part of DataM8.

DataM8 is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

DataM8 is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program. If not, see <https://www.gnu.org/licenses/>.
"""

# generated by datamodel-codegen:
#   filename:  zone.json

from __future__ import annotations

from typing import Annotated, Optional

from pydantic import BaseModel, ConfigDict, Field


class Zone(BaseModel):
    """
    Defines a high-level layer or zone, typically used to clearly seperate different states of data processing, e.g. bronze, silver, gold, semantic.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    name: Annotated[
        str, Field(description="Logical name of the zone (e.g., Raw, Core, Curated)")
    ]
    targetName: Annotated[
        str,
        Field(
            description="Target system name for the zone (e.g., Bronze, Silver, Gold)"
        ),
    ]
    displayName: Annotated[str, Field(description="Human-readable display name")]
    localFolderName: Annotated[
        Optional[str],
        Field(description="Local folder name used in file system structure"),
    ] = None
